export const catalogoProds = [{
        id: "1",
        title: "Jupiter",
        price: 950,
        stock: 10,
        img: "https://gdurl.com/rA4y",
        category: "planetas",
    },
    {
        id: "2",
        title: "Marte",
        price: 1200,
        stock: 5,
        img: "https://gdurl.com/1ePk",
        category: "planetas",
    },
    {
        id: "3",
        title: "Tierra",
        price: 800,
        stock: 6,
        img: "https://gdurl.com/D2Yl",
        category: "planetas",
    },
    {
        id: "4",
        title: "Saturno",
        price: 700,
        stock: 10,
        img: "https://gdurl.com/BSGk",
        category: "planetas",
    },
    {
        id: "5",
        title: "Flores",
        price: 450,
        stock: 4,
        img: "https://gdurl.com/s_05",
        category: "flores",
    },
    {
        id: "6",
        title: "Florcitas",
        price: 550,
        stock: 6,
        img: "https://gdurl.com/AhIf",
        category: "flores",
    },
];